server:
  port: 8080

spring.application.name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
